version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: webacademy_livros
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - rede_db
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=pass123
    depends_on:
      - db
    networks:
      - rede_db
  
  front:
    build: ./webacademy-livros-frontend
    restart: always
    ports:
      - 8000:80
    env_file:
      - ./webacademy-livros-frontend/.env
    depends_on:
      - db
    networks:
      - rede_db

  back:
    build: ./webacademy-livros-backend
    restart: always
    ports:
      - 4444:4444
    env_file:
      - ./webacademy-livros-backend/.env
    depends_on:
      - db
    networks:
      - rede_db

networks:
  rede_db:
    driver: bridge
  
volumes:
  vol_mysql: